language: java

notifications:
  email: false
  slack:
    secure: "nuX1zHeDPx3rEYb3gGhFgGWKggYug1OFaUZxV+lK74YIi/4pFynWIuvfuzfgInEb5Qj5mrKrc5OTRWcYBKCjJDHUTqU11crhalAyVrTMTKAYw3kIQqE21mBphKqDVRChMXutU9w5MOWMSDV5LLX9f2kU4yNy05eaTcr8YGTlS3l+UWOM/3Pcw6ZrRSGJJws2JyxtWXPsftIqWAmCuVJVS2gsZGU9IE1dJXwDx2Fiypeyuh4AtmByKOsKgDgLmUi/bV6lFAuQofFCOJpO7mBu4QwySolajnQQlT78KNQjvToo/IfiiasO81GoP1+mVZbZyCLw92kIfoYqWI6yDZzya96lM8Eba6F2y5D+CfDuSI5nhKR9t8U+BJvsz0yxCamu2mQNY/jl/zUZUTgZHLHp33HKloZOZggxCMTQNs5YOlKItCvES5q1k2YHWzw6oJTnhWNa5fdjcLDdiJHd5gIEBVraLWHsM9btQvASgcewMGoe52vV3GmsAF43U/mtsON0H54OsTij/x2QWlPIxPlRtdOFnZgo1LDWDDsYpmjfXjUGRik3D9ggLQKkSfj8Mpu/EFGYzT7MGqkNsCgfzMIYqRBelPqAtpiHkgxdTXTRiYZ0l0Q36krktFHtKdhxqQ2lSz2bn9c16Q7aDFdtl2w2pZCokvPezGpLRQ2pHmGlGcs="
jdk:
  - oraclejdk8

services:
  - mysql

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - $(! $TRAVIS_SECURE_ENV_VARS) || (openssl aes-256-cbc -K $encrypted_e55aacca67f1_key -iv $encrypted_e55aacca67f1_iv
    -in secrets.tar.enc -out secrets.tar -d && tar xvf secrets.tar)
  - $(! $TRAVIS_SECURE_ENV_VARS) || ( if [ "$TRAVIS_BRANCH" == "master" ]; then tar xvf secrets-prod.tar; else tar xvf secrets-lab.tar; sed -i '/SPRING_PROFILES_ACTIVE/s/$/,lab/' Dockerfile; fi; rm secrets*.tar )
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost'"
  - mysql -u root -e "create database if not exists test default charset utf8;"

before_deploy: ./gradlew bootRepackage

deploy:
  - provider: gae
    project: coduno
    version: "${TRAVIS_COMMIT:0:7}-${TRAVIS_BUILD_NUMBER}"
    skip_cleanup: true
    on:
      branch: master
  - provider: gae
    project: coduno-lab
    version: "${TRAVIS_COMMIT:0:7}-${TRAVIS_BUILD_NUMBER}"
    skip_cleanup: true
    on:
      branch: dev
