service: platform
runtime: custom
vm: true
api_version: 1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.8

network:
  forwarded_ports:
  - 8090
